export const presets = [
	{
		description: "Unleash your creativity with Pixel Wizard, your portal to the artistic universe.",
		slug: "pixel_wizard",
		image: "/placeholder.png",
		links: [
			{ id: 1, url: "https://pixelwizard.co/portfolio", title: "Artistic Portfolio" },
			{ id: 2, url: "https://pixelwizard.co/gallery", title: "Magic Gallery" },
			{ id: 3, url: "https://pixelwizard.co/tutorials", title: "Art Tutorials" },
			{ id: 4, url: "https://pixelwizard.co/community", title: "Join Community" },
		],
		buttons: [
			{ id: 1, url: "https://facebook.com/nova_skylar", icon: "simple-icons:bandcamp" },
			{ id: 2, url: "https://instagram.com/nova_skylar", icon: "simple-icons:instagram" },
			{ id: 3, url: "https://twitter.com/nova_skylar", icon: "simple-icons:twitter" },
		],
		settings: {
			backgroundColor: "#1abc9c",
			slugTextColor: "#2c3e50",
			slugTextWeight: "700",
			slugTextSize: "1.75rem",
			headerTextColor: "#ffffff",
			buttonBackgroundColor: "#34495e",
			buttonHoverBackgroundColor: "#2c3e50",
			buttonIconColor: "#ffffff",
			isButtonShadow: true,
			buttonShadowColor: "rgba(0, 0, 0, 0.2)",
			linkBackgroundColor: "#ecf0f1",
			linkHoverBackgroundColor: "#bdc3c7",
			linkTextColor: "#2c3e50",
			linkBorderRadius: "10px",
			linkPadding: "10px 15px",
			isLinkShadow: true,
			linkShadowColor: "rgba(0, 0, 0, 0.2)",
		},
	},
	{
		description: "Join Skylar Nova on a mission to connect, inspire, and thrive in the digital cosmos.",
		slug: "nova_skylar",
		image: "/placeholder.png",
		links: [
			{ id: 1, url: "https://novaskylar.com/subscribe", title: "Subscribe to Newsletter" },
			{ id: 2, url: "https://novaskylar.com/events", title: "Upcoming Events" },
			{ id: 3, url: "https://novaskylar.com/blog", title: "Read Our Blog" },
		],
		buttons: [
			{ id: 1, url: "https://facebook.com/nova_skylar", icon: "simple-icons:facebook" },
			{ id: 2, url: "https://linkedin.com/in/skylar_nova", icon: "simple-icons:linkedin" },
		],
		settings: {
			backgroundColor: "#f39c12",
			slugTextColor: "#2c3e50",
			slugTextWeight: "900",
			slugTextSize: "1.75rem",
			headerTextColor: "#ffffff",
			buttonBackgroundColor: "#2d3436",
			buttonHoverBackgroundColor: "#1e272e",
			buttonIconColor: "#ffffff",
			isButtonShadow: true,
			buttonShadowColor: "rgba(0, 0, 0, 0.2)",
			linkBackgroundColor: "#ffeaa7",
			linkHoverBackgroundColor: "#fab1a0",
			linkTextColor: "#2c3e50",
			linkBorderRadius: "10px",
			linkPadding: "10px 15px",
			isLinkShadow: true,
			linkShadowColor: "rgba(0, 0, 0, 0.2)",
		},
	},
	{
		description: "Experience high-tech innovation with Blitz Corp, where the future is now.",
		slug: "blitz_corp",
		image: "/placeholder.png",
		links: [
			{ id: 1, url: "https://blitzcorp.com/solutions", title: "Innovative Solutions" },
			{ id: 2, url: "https://blitzcorp.com/careers", title: "Join Our Team" },
		],
		buttons: [
			{ id: 1, url: "https://twitter.com/blitz_corp", icon: "simple-icons:twitter" },
			{ id: 2, url: "https://linkedin.com/company/blitz_corp", icon: "simple-icons:linkedin" },
			{ id: 3, url: "https://youtube.com/blitzcorp", icon: "simple-icons:youtube" },
		],
		settings: {
			backgroundColor: "#8e44ad",
			slugTextColor: "#ffffff",
			slugTextWeight: "800",
			slugTextSize: "1.75rem",
			headerTextColor: "#c0392b",
			buttonBackgroundColor: "#ffffff",
			buttonHoverBackgroundColor: "#dcdcdc",
			buttonIconColor: "#8e44ad",
			isButtonShadow: true,
			buttonShadowColor: "rgba(0, 0, 0, 0.2)",
			linkBackgroundColor: "#f7f1e3",
			linkHoverBackgroundColor: "#d1ccc0",
			linkTextColor: "#8e44ad",
			linkBorderRadius: "10px",
			linkPadding: "10px 15px",
			isLinkShadow: true,
			linkShadowColor: "rgba(0, 0, 0, 0.2)",
		},
	},
	{
		description: "Uncover the mysteries of digital art with Mirage Studios, where imagination has no limits.",
		slug: "mirage_studios",
		image: "/placeholder.png",
		links: [
			{ id: 1, url: "https://miragestudios.com/art", title: "Digital Art" },
			{ id: 2, url: "https://miragestudios.com/academy", title: "Join Our Academy" },
			{ id: 3, url: "https://miragestudios.com/exhibitions", title: "Exhibitions" },
		],
		buttons: [{ id: 1, url: "https://youtube.com/miragestudios", icon: "simple-icons:youtube" }],
		settings: {
			backgroundColor: "#3498db",
			slugTextColor: "#ffffff",
			slugTextWeight: "bold",
			slugTextSize: "1.75rem",
			headerTextColor: "#e67e22",
			buttonBackgroundColor: "#2c3e50",
			buttonHoverBackgroundColor: "#1abc9c",
			buttonIconColor: "#ffffff",
			isButtonShadow: true,
			buttonShadowColor: "rgba(0, 0, 0, 0.2)",
			linkBackgroundColor: "#dfe6e9",
			linkHoverBackgroundColor: "#b2bec3",
			linkTextColor: "#2c3e50",
			linkBorderRadius: "10px",
			linkPadding: "10px 15px",
			isLinkShadow: true,
			linkShadowColor: "rgba(0, 0, 0, 0.2)",
		},
	},
]
